### ISSUE TITLE
Bridging perimeters should Always print before bridging infill

### ISSUE THREAD

**Issue by nhopfen** [rvmn/Pleccer#11]
This is related to the arc infill not anchoring to anything and drooping down on parts on 4 legs such as this https://thangs.com/designer/models/3d-model/62763 [...]

**Describe the solution you'd like**
On bridges, perimeters should ALWAYS be printed before infill, to provide an anchor point. This should be FORCED regardless of the "infill before perimeters" or the "external perimeters first" settings.

At the moment infill always prints before, whatever your settings, which causes prints to fail.

Keep up the great work

**Comment by nhopfen** [comment]
![IMG_20230406_150319_282](https://user-images.githubusercontent.com/24226597/230487839-ca6ad1ee-0725-444a-ae7c-0b2036c727d5.jpg)
![IMG_20230406_162801_929](https://user-images.githubusercontent.com/24226597/230487840-85200bb9-7262-4bd5-9729-3e836a979083.jpg)
![IMG_20230406_162750_039](https://user-images.githubusercontent.com/24226597/230487845-4cb07cac-f1e4-466a-8a24-d54d40305c51.jpg)
![IMG_20230406_150323_583](https://user-images.githubusercontent.com/24226597/230487847-c21e7008-f56a-4698-9ba9-299c3994dee7.jpg)

**Comment by nhopfen** [comment]
on a free-floating part, this outer bridging perimeter would then droop down but in my experience, this just means the loop could possibly act as a makeshift support layer, while also creating air turbulence that potentially throws the cooling back up towards the infill while it prints. and then as long as the infill is nice subsequent layers correct themselves quickly. Some people might prefer an toggleable option named "Bridging perimeters first"

**Comment by nhopfen** [comment]
Sorry, my fault, I missed the "Overhang infill before perimeter" check box

**Comment by rvmn** [comment]
ok, i missed this issue, sorry, i thought github would inform me on issues automatically..

yeah, when perimeters should be printed is a bit of a subjective issue, but i think overhanging parts are always best infill first, also bridges, because they should not rely on the perimeters as anchors but on correct support lines/pillars below it. 
the perimeters/walls should just be to give a nice wall, and that works best if printed last (so anchored well on infill).

**Comment by rvmn** [comment]
New feature in the coming version is autogenerated bridge supports (infill first):![Schermafdruk van 2023-04-19 14-53-02](https://user-images.githubusercontent.com/8228964/233080714-88ae82ba-0ccb-454d-b23f-3e97bbb723e5.png)

**Comment by nhopfen** [comment]
"> ok, I missed this issue, sorry, I thought github would inform me on issues automatically.."

No problem I think that's because I closed the ticket when I realized that the "Overhang infill before perimeter" was there.

Looking forward to testing the upcoming feature though
