### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Marco-Pietersen** [rvmn/Pleccer#24]
### What happened?

As you are aware the build chain isn't working. I have therefor attempted to build the tool myself, but there are plenty issues. 

1. I had to update the batch file as somehow vswhere command couldn't handle the version array. Workaround: Updated it manually to 17
2. cmake isn't in the required software and not on my machine as part of something else. Solution: install cmake
3. cmake reports CMAKE_C_COMPILER / CMAKE_CXX_COMPILER not set; I've found that this is done in the CMakeLists.txt. CXX refers to a 'clang' compiler, but C compiler is nowhere mentioned. 
Unable to proceed there. 

I understand this is a fork, so possibly you need to update it? 
Or update the windows requirements
Or get a version built for windows.

I do appreciate your time and effort, let that be clear!

### Project file & How to reproduce

Pulled master and ran build_win.bat

C:\_dev\SuperPleccer\SuperSlicer>build_win.bat -d=..\SuperPleccer-deps -r=console
VSWHERE=C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
MSVC_FILTER=-products Microsoft.VisualStudio.Product.Community -version 17
where command="C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products Microsoft.VisualStudio.Product.Community -version 17 -nologo -property installationPath
**********************************************************************
** Build Config: RelWithDebInfo
** Target Arch:  x64
** Build Steps:  all
** Run App:      console
** Deps path:    C:\_dev\SuperPleccer\SuperPleccer-deps
** Using Microsoft Visual Studio installation found at:
**  C:\Program Files\Microsoft Visual Studio\2022\Community
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
Cleaning deps\build ...
Cleaning C:\_dev\SuperPleccer\SuperPleccer-deps ...
-- Building for: NMake Makefiles
CMake Warning (dev) at CMakeLists.txt:23 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:23 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

ERROR: *** Build process failed at deps step. ***

### Version

Master

### Operating system

Windows 10

### Printer model

Ultimaker S2+

**Comment by rvmn** [comment]
Please fill in the [poll](https://github.com/rvmn/SuperPleccer/discussions/27)
Thank you!
