### ISSUE TITLE
error when starting .appimage on kali.

### ISSUE THREAD

**Issue by NanashiTheNameless** [rvmn/Pleccer#6]
### What happened?

i downloaded and renamed the file in my home directory... then did `chmod +x ~/.Pleccer.AppImage` then ran `exec ~/.Pleccer.AppImage` and it then spits out the error
`[2023-03-18 18:03:42.097005] [0x00007fb07ea76880] [trace]   Initializing StaticPrintConfigs
[2023-03-18 18:03:42.302992] [0x00007fb07ea76880] [error]   Uncaught exception: boost::filesystem::status: Permission denied [system:13]: "/root/PrusaSlicer/deps/build/destdir././/local/ssl/cert.pem"
Unhandled unknown exception; terminating the application.`
and crashes

### Project file & How to reproduce

i included my prusa configs here in case thats important
[PrusaConfigs.zip](https://github.com/rvmn/SuperPleccer/files/11009706/PrusaConfigs.zip)

### Version

Alpha4

### Operating system

OS: Kali GNU/Linux Rolling x86_64 
Host: MG-VCTR002-2060 Standard 
Kernel: 6.1.0-kali5-amd64 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Xfce 4.18 
WM: Xfwm4 
Terminal: tilix 
CPU: Intel i7-10750H (12) @ 5.000GHz 
GPU: Intel CometLake-H GT2 [UHD Graphics] 
GPU: NVIDIA GeForce RTX 2060 Mobile 
Memory: 2567MiB / 64145MiB 

### Printer model

Ender 3 V2

**Comment by rvmn** [comment]
Ah, the AppImage wasn't working, 
reuploaded the working one now, please try.

Thanks for giving the notice :+1:
